### ISSUE TITLE
Provide a "validate" command

### ISSUE THREAD

**Issue by elleuca** [structurizr/cli#18] opened 2020-11-23 10:48 UTC
Could be good to have a `validate` command to check if dsl file is well formed without pushing to structurizr.com

**Comment by simonbrowndotje** [comment] 2020-11-23 11:04
The conversion from the DSL format to the JSON workspace format is all done client-side, by the CLI itself, so you will see any problems with invalid DSL before pushing to Structurizr. Are you seeing some issues?

**Comment by elleuca** [comment] 2020-11-23 13:49
> The conversion from the DSL format to the JSON workspace format is all done client-side, by the CLI itself, so you will see any problems with invalid DSL before pushing to Structurizr. 

Oh, nice to know.

> Are you seeing some issues?

Tried just now, I got following error. But checked DSL file currently doesn't define any custom view, relying on default ones, and we have ~ 50 diagrams.

```console
$ ./structurizr.sh export  -workspace current.dsl  -format json
Structurizr CLI v1.5.0
Exporting workspace from current.dsl
 - loading workspace from DSL
 - no views defined; creating default views
2020-11-23 14:37:29.866 ERROR 11322 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:779) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at com.structurizr.cli.StructurizrCliApplication.main(StructurizrCliApplication.java:69) ~[classes!/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[structurizr-cli-1.5.0.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:109) ~[structurizr-cli-1.5.0.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[structurizr-cli-1.5.0.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[structurizr-cli-1.5.0.jar:na]
Caused by: java.lang.NullPointerException: null
        at java.base/java.io.File.<init>(File.java:279) ~[na:na]
        at com.structurizr.cli.ExportCommand.run(ExportCommand.java:118) ~[classes!/:na]
        at com.structurizr.cli.StructurizrCliApplication.run(StructurizrCliApplication.java:40) ~[classes!/:na]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        ... 13 common frames omitted
```

**Comment by simonbrowndotje** [comment] 2020-11-23 13:51
That's probably a duplicate of #16 and #17 ... as a workaround, try adding the `-output` parameter.

**Comment by elleuca** [comment] 2020-11-23 13:57
> That's probably a duplicate of #16 and #17 ... as a workaround, try adding the `-output` parameter.

👍

**Closed** 2020-11-23 14:02 UTC

**Comment by florianmutter** [comment] 2020-12-02 13:24
I would also like to have a verify command but for different reasons: I would like to setup a ci pipeline for pull requests on the documentation but I do only want merged changes to be pushed to the actual workspace.

**Comment by simonbrowndotje** [comment] 2020-12-02 15:19
If you want to validate the DSL, you can do something like the following (which will fail is the DSL isn't valid):

```
./structurizr.sh export -format json -workspace <workspace.dsl>
```

In any case, a `push` will also fail (on the client-side) if the DSL isn't valid.

**Comment by florianmutter** [comment] 2020-12-02 15:48
That works! Thank you very much
